### ISSUE TITLE
Sugestão: Renomear módulo NFe::Reader para NFeReader

### ISSUE THREAD

**Issue by franciscomxs** [eduBKR/nfe_reader#1]
Eu tenho um model na aplicação chamado NFe que precisa existir para ter persistência e isso conflita com o uso da biblioteca. Vou renomear pra invoice pra poder usar essa gem, mas seria bem legal usar um nome menos genérico como modulo da biblioteca. Se aceitarem a sugestão eu mesmo mando um pull request ;)

```
class NFe
  belongs_to :company
   # attributes: key, xml_file
end

class Company
  has_many :nfes, dependent: :destroy
end
```

**Comment by eduBKR** [comment]
Sim, estava pensando isso mesmo, só preciso de um nome para trocar, nem que seja Base, ou algo do tipo.
So espera um pouco que eu tenho umas correções que estou terminando, vai sair a versao 1.0.6, se voce me ajudar ja deixo isso nessa versão.

**Comment by franciscomxs** [comment]
Fechado então, ajudo sim.
Acho que o nome da biblioteca é o mais indicado pra colocar no módulo.

```
NFeReader::NFe.new(file)
```

**Comment by eduBKR** [comment]
Alterado e disponivel já renomeado na versão 1.0.6.
