### ISSUE TITLE
Qual modelo de nfe este reader trabalha ? 2.0 e 3.1 ?

### ISSUE THREAD

**Issue by rcoproc** [eduBKR/nfe_reader#5]
Olá Edu, parabéns pela iniciativa.

Uma dúvida, qual modelo de nfe este sua gem funciona a 3.1 também ?? ou só a 2.0 ??

E a 4.0 tem idéia de melhorar ??

Atte.

Ricardo Oliveira

**Comment by eduBKR** [comment]
OI, esta rodando na 3.1, acredito que tenha que fazer alguma adaptação para funcionar nas versões abaixo, pois pelo o que eu me lembro a tag de data de emissão nas versões mais antigas era apenas a data, e na 3 em diante é data e hora.
Com relação a 4.0, ainda não pensei, mas os meus planos é fazer uma integração em ruby com o SEFAZ, já estou começando a estrutura o que precisa.

**Comment by rcoproc** [comment]
Beleza , parabéns e obrigado.. vou fazer um clone e te acompanhar no que precisar de ajuda se estiver a fim.

Abraço

Ricardo
